name: Vitest CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Vitest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          install: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Build
        run: pnpm run build

      - name: Run vitest
        run: pnpm run test
